const translation = {
  "en": {
    "home": {},
    "html": {
      "name-add-block": "Add Block",
      "nav": ["Settings", "Textures", "Code Pieces"],
      "main-fab-btn": ["Propertie", "Control", "Object", "Data", "Start"],
      "files-fab": ["Draw", "Files", "URL"],
      "btns-edit-params": ["Code", "Text", "Ok", "Add"],
      "formuls": {
        "group-name": [
          "Data",
          "MouseEvent",
          "Textures",
          "Math",
          "Properties",
          "Logic",
          "Function",
          "My-func",
          "Else"
        ],
        "btns": [
          "+Create",
          "mouseX",
          "mouseY",
          "colisionWithTouch({ ",
          "TypeOfClick",
          "Target",
          "tappedElement",
          "hgtrthgfsddfeghj",
          "pow",
          "random",
          "sqrt",
          "sin",
          "cos",
          "tan",
          "asin",
          "acos",
          "atan",
          "atan2",
          "max",
          "min",
          "abs",
          "sign",
          "ceil",
          "floor",
          "round",
          "trunc",
          "getModule",
          "log",
          "log10",
          "PI",
          ".x",
          ".y",
          ".width",
          ".height",
          ".color",
          ".radius",
          ".direction",
          ".startAngle",
          ".endAngle",
          "DisplayWidth",
          "DisplayHeight",
          "=",
          "!=",
          ">",
          "<",
          ">=",
          "<=",
          "and",
          "or",
          "no",
          "true",
          "false",
          "undefined",
          "showMessege",
          "prompt",
          "confirm",
          "JSON.stringify",
          "JSON.parse",
          "joinStrings",
          "degToRadian",
          "randomInteger",
          "colisionBetween",
          "oppositeColision",
          "distanceBetween",
          ".length",
          ".indexOf",
          ".lastIndexOf",
          ".includes",
          ".isArray",
          "Object.keys",
          "+Create",
          "[",
          "]",
          "{",
          "}",
          "()=>",
          "ternary",
          'ADD',
          "CodeInHTML"
        ],
      },
      "message": {
        "writeText": "Write Text",
        "writeCode": "Write Code",
        "writeName": "Write texture name",
        "writeURL": "Write URL",
        "createFunction": "Create Function",
        "createData": "Create Data",
        "createPiece": "Create new piece",
        "delete": "Delete",
        "btns": ["CANCEL", "OK"],
        "notRecomended": [
          "Not recommended",
          "Use the URL instead",
          "Large images will take a long time to process"
        ],
        "alreadyIncledes": [
          "ALREADY EXISTS",
          "Starts with a number",
          "Only Latin"
        ]
      },
    }
  },
  "ua": {
    "home": {},
    "html": {
      "name-add-block": "Додати блок",
      "nav": ["Налаштування", "Текстури", "Фрагменти"],
      "main-fab-btn": ["Властивості", "Керування", "Об'єкти", "Дані", "Старт"],
      "files-fab": ["Малювати", "Файли", "URL"],
      "btns-edit-params": ["Код", "Текст", "ОК"],
      "formuls": {
        "group-name": [
          "Дані",
          "ПодіїМиші",
          "Текстури",
          "Математика",
          "Властивості",
          "Логіка",
          "Функція",
          "Мої-функції",
          "Інше"
        ],
        "btns": [
          "+Створити",
          "мишаX",
          "мишаY",
          "зіткненняЗДотиком({",
          "ТипКліка",
          "Ціль",
          "натиснутийЕлемент",
          "hgtrthgfsddfeghj",
          "степінь",
          "випадкове",
          "корінь",
          "синус",
          "косинус",
          "тангенс",
          "асинус",
          "акосинус",
          "атангенс",
          "атангенс2",
          "максимум",
          "мінімум",
          "абсолютне",
          "знак",
          "округленняВгору",
          "округленняВниз",
          "округлення",
          "цілаЧастина",
          "отриматиМодуль",
          "логарифм",
          "логарифм10",
          "Пі",
          ".х",
          ".у",
          ".ширина",
          ".висота",
          ".колір",
          ".радіус",
          ".напрямок",
          ".початковийКут",
          ".кінцевийКут",
          "ШиринаЕкрана",
          "ВисотаЕкрана",
          "=",
          "!=",
          ">",
          "<",
          ">=",
          "<=",
          "і",
          "або",
          "ні",
          "правда",
          "хиба",
          "неозначено",
          "показатиПовідомлення",
          "запит",
          "підтвердити",
          "JSON.stringify",
          "JSON.parse",
          "об'єднатиРядки",
          "градусиВРадіани",
          "випадковеЦіле",
          "зіткненняМіж",
          "повнеЗіткнення",
          "відстаньМіж",
          ".довжина",
          ".індексЗаЗначенням",
          ".індексЗаЗначеннямЗКінця",
          ".містить",
          ".масив",
          "Об'єкт.ключі",
          "+Створити",
          "[",
          "]",
          "{",
          "}",
          "()=>",
          "тернарний",
          "+",
          "КодВhtml"
        ]
      },
      "message": {
        "writeText": "Напишіть текст",
        "writeCode": "Напишіть код",
        "writeName": "Назва текстури",
        "writeURL": "Напишіть URL",
        "createFunction": "Створити функцію",
        "createData": "Створити змінну",
        "createPiece": "Створити фрагмент",
        "delete": "Видалити",
        "btns": ["СКАСУВАТИ", "ОК"],
        "notRecomended": [
          "Не рекомендується",
          "Використовуйте замість цього URL",
          "Великі зображення оброблюватимуться довго"
        ],
        "alreadyIncledes": [
          "ВЖЕ ІСНУЄ",
          "Починається з числа",
          "Тільки латиниця"
        ]
      },
    }
  },
  "ru": {
    "home": {},
    "html": {
      "name-add-block": "Добавить блок",
      "nav": ["Настройки", "Текстуры", "Кусочки"],
      "main-fab-btn": ["Свойства", "Управление", "Объекты", "Данные", "Старт"],
      "files-fab": ["Рисовать", "Файлы", "URL"],
      "btns-edit-params": ["Код", "Текст", "Ок"],
      "formuls": {
        "group-name": [
          "Данные",
          "СобытиеМыши",
          "Текстуры",
          "Математика",
          "Свойства",
          "Логика",
          "Функция",
          "Мои-функции",
          "Другое"
        ],
        "btns": [
          "+Создать",
          "мышьX",
          "мышьY",
          "столкновениеСКасанием({ ",
          "ТипКлика",
          "Цель",
          "нажатыйЭлемент",
          "hgtrthgfsddfeghj",
          "степень",
          "случайное",
          "корень",
          "синус",
          "косинус",
          "тангенс",
          "асинус",
          "акосинус",
          "атангенс",
          "атангенс2",
          "максимум",
          "минимум",
          "абсолютное",
          "знак",
          "округлениеВверх",
          "округлениеВниз",
          "округление",
          "целаяЧасть",
          "получитьМодуль",
          "логарифм",
          "логарифм10",
          "Пи",
          ".х",
          ".у",
          ".ширина",
          ".высота",
          ".цвет",
          ".радиус",
          ".направление",
          ".начальныйУгол",
          ".конечныйУгол",
          "ШиринаЭкрана",
          "ВысотаЭкрана",
          "=",
          "!=",
          ">",
          "<",
          ">=",
          "<=",
          "и",
          "или",
          "нет",
          "правда",
          "ложь",
          "неопределено",
          "показатьСообщение",
          "запрос",
          "подтвердить",
          "JSON.stringify",
          "JSON.parse",
          "объединитьСтроки",
          "градусыВРадианы",
          "случайноеЦелое",
          "столкновениеМежду",
          "полноеСтолкновение",
          "расстояниеМежду",
          ".длина",
          ".индексПоЗначению",
          ".индексПоЗначениюСКонца",
          ".включает",
          ".массив",
          "Объект.ключи",
          "+Создать",
          "[",
          "]",
          "{",
          "}",
          "()=>",
          "тернарный",
          "+",
          "КодВhtml"
        ]
      },
      "message": {
        "writeText": "Напиши текст",
        "writeCode": "Напиши код",
        "writeName": "Название текстуры",
        "writeURL": "Напиши URL",
        "createFunction": "Создать функцию",
        "createData": "Создать переменную",
        "createPiece": "Создать кусочок",
        "delete": "Удалить",
        "btns": ["ОТМЕНА", "ОК"],
        "notRecomended": [
          "Не рекомендуется",
          "Используйте вместо этого URL",
          "Большие изображения будут обрабатываться долго"
        ],
        "alreadyIncledes": [
          "УЖЕ СУЩЕСТВУЕТ",
          "Начинается с числа",
          "Только латиница"
        ]
      },
    }
  }
};
